version: '2'
services:
  database:
    image: mysql
    container_name: mysql
#    command: mysqld
    volumes:
      - ./dbcreation.sql:/tmp/dbcreation.sql
#      - ./import.sh:/tmp/import.sh
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "refund"
      MYSQL_USER: "refund_user"
      MYSQL_PASSWORD: "refund_user"
      MYSQL_ROOT_PASSWORD: "refund_root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
